name: Build & Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        Platforms: [x86, x64, Any CPU]
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Setup nuget.exe
      uses: nuget/setup-nuget@v1
      with:
        nuget-version: latest
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1

    - name: Restore dependencies
      run: MSBuild.exe -t:restore -p:Configuration=Release "-p:Platform=${{ matrix.Platforms }}"
    - name: Get CurrentDirectory path
      # ref : https://takao-hp.com/work/powershell-dir/
      run: $CurrentDirectory = (Convert-Path .)

    - name: Build
      run: MSBuild.exe -p:Configuration=Release "-p:Platform=${{ matrix.Platforms }}" -p:OutputPath=$CurrentDirectory/bin
    - name: Test
      run: dotnet test --no-build --verbosity normal -p:Configuration=Release "-p:Platform=${{ matrix.Platforms }}"
